### ISSUE TITLE
Evaluate props inside stylesheet?

### ISSUE THREAD

**Issue by k1r0s** [k1r0s/preact-stylesheet-decorator#3]
Instead of providing an string, `stylesheet` can be tweaked to accept a function that evaluates to a string having received props. 

```javascript
const Comp = stylesheet(
props => `
  span {
    color: ${props.primary ? 'cyan' : 'black' }
  }
`, 
props => (
  <div>
    <span>something</span>
  </div>
))
```

**Comment by adyasha1018** [comment]
Hello,
I have the code like below. 

`import { stylesheet } from "stylesheet-decorator[/preact]";

const style = `div {
		font-family: 'Courier New', Courier, monospace;
		font-size: 16px;
		color: red;
		text-align: center;
	}`

export default class Hello extends Component {
	@stylesheet(style)
	render() {
		return <div>Welcome 2 Preact World!!!</div>;
	}
}`

For this I am getting following error: for **@**
`Module build failed: SyntaxError: ../components/hello/src/hello.js: Unexpected token`.

Any help would be appreciated.

**Comment by k1r0s** [comment]
did you added needed dependencies in order to compile decorators?

**Comment by adyasha1018** [comment]
Yes, I forgot to add the proper loader. I added like this..
```
{
				test: /\.css$/,
				use: [
					"style-loader",
					{
						loader: "css-loader",
						options: {
							modules: {
								mode: "local",
								localIdentName: "[path][name]__[local]--[hash:base64:5]",
								context: path.resolve(__dirname, "src"),
								hashPrefix: "my-custom-hash",
							},
						},
					},
				],
			},
```
it worked.
Thanks a lot.

**Comment by k1r0s** [comment]
closing this as the main issue is not going to happend and unrelated contnt
