### ISSUE TITLE
[Question] Browser support

### ISSUE THREAD

**Issue by thomascgray** [k1r0s/preact-stylesheet-decorator#4]
Am I correct in thinking this library achieves its "scoped-ness" via `<style>` tags with a `scoped` property?

In which case, I don't think that is supported anymore? https://caniuse.com/#feat=style-scoped

**Comment by k1r0s** [comment]
Hi @thomascgray 

well, basically it does it by overriding your css selectors under the hood using this module https://www.npmjs.com/package/scope-css

The `scoped` property on <style/> tags does nothing but align by convention.. like vue and other frameworks does
